create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports res_n]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports res_n]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports shift_in]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports shift_in]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports shift_out]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports shift_out]
set_output_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks clk] -max -add_delay 5.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports empty]
set_output_delay -clock [get_clocks clk] -max -add_delay 5.000 [get_ports empty]
set_output_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports full]
set_output_delay -clock [get_clocks clk] -max -add_delay 5.000 [get_ports full]
