create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]




set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports {data_in[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports res_n]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports res_n]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports shift_in]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports shift_in]
set_input_delay -clock [get_clocks clk] -min -add_delay 4.000 [get_ports shift_out]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports shift_out]
set_output_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks clk] -max -add_delay 5.000 [get_ports {data_out[*]}]
set_output_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports empty]
set_output_delay -clock [get_clocks clk] -max -add_delay 5.000 [get_ports empty]
set_output_delay -clock [get_clocks clk] -min -add_delay 1.000 [get_ports full]
set_output_delay -clock [get_clocks clk] -max -add_delay 5.000 [get_ports full]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[0]}]
set_property PACKAGE_PIN A12 [get_ports {data_in[28]}]
set_property PACKAGE_PIN A13 [get_ports {data_in[27]}]
set_property PACKAGE_PIN A14 [get_ports {data_in[26]}]
set_property PACKAGE_PIN A15 [get_ports {data_in[25]}]
set_property PACKAGE_PIN A17 [get_ports {data_in[24]}]
set_property PACKAGE_PIN A18 [get_ports {data_in[23]}]
set_property PACKAGE_PIN A19 [get_ports {data_in[22]}]
set_property PACKAGE_PIN A20 [get_ports {data_in[21]}]
set_property PACKAGE_PIN A22 [get_ports {data_in[20]}]
set_property PACKAGE_PIN A23 [get_ports {data_in[19]}]
set_property PACKAGE_PIN A24 [get_ports {data_in[18]}]
set_property PACKAGE_PIN A25 [get_ports {data_in[17]}]
set_property PACKAGE_PIN AA4 [get_ports {data_in[14]}]
set_property PACKAGE_PIN AA5 [get_ports {data_in[13]}]
set_property PACKAGE_PIN AA7 [get_ports {data_in[12]}]
set_property PACKAGE_PIN AA12 [get_ports {data_in[8]}]
set_property PACKAGE_PIN AA13 [get_ports {data_in[7]}]
set_property PACKAGE_PIN AB1 [get_ports {data_in[6]}]
set_property PACKAGE_PIN AB2 [get_ports {data_in[5]}]
set_property PACKAGE_PIN AB4 [get_ports {data_in[4]}]
set_property PACKAGE_PIN AB5 [get_ports {data_in[3]}]
set_property PACKAGE_PIN AB6 [get_ports {data_in[2]}]
set_property PACKAGE_PIN AB7 [get_ports {data_in[1]}]
set_property PACKAGE_PIN AB9 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[8]}]

set_property PACKAGE_PIN R22 [get_ports clk]
set_property PACKAGE_PIN AA2 [get_ports empty]
set_property PACKAGE_PIN AA3 [get_ports full]
set_property PACKAGE_PIN A8 [get_ports res_n]
set_property PACKAGE_PIN A9 [get_ports shift_in]
set_property PACKAGE_PIN A10 [get_ports shift_out]
set_property PACKAGE_PIN AD3 [get_ports {data_in[16]}]
set_property PACKAGE_PIN AD4 [get_ports {data_in[15]}]
set_property PACKAGE_PIN AD6 [get_ports {data_in[11]}]
set_property PACKAGE_PIN AD8 [get_ports {data_in[10]}]
set_property PACKAGE_PIN AD9 [get_ports {data_in[9]}]
set_property PACKAGE_PIN AB10 [get_ports {data_out[31]}]
set_property PACKAGE_PIN AB11 [get_ports {data_out[30]}]
set_property PACKAGE_PIN AB12 [get_ports {data_out[29]}]
set_property PACKAGE_PIN AC1 [get_ports {data_out[28]}]
set_property PACKAGE_PIN AC2 [get_ports {data_out[27]}]
set_property PACKAGE_PIN AC3 [get_ports {data_out[26]}]
set_property PACKAGE_PIN AC4 [get_ports {data_out[25]}]
set_property PACKAGE_PIN AC6 [get_ports {data_out[24]}]
set_property PACKAGE_PIN AC7 [get_ports {data_out[23]}]
set_property PACKAGE_PIN AC8 [get_ports {data_out[22]}]
set_property PACKAGE_PIN AC9 [get_ports {data_out[21]}]
set_property PACKAGE_PIN AC11 [get_ports {data_out[20]}]
set_property PACKAGE_PIN AC12 [get_ports {data_out[19]}]
set_property PACKAGE_PIN AC13 [get_ports {data_out[18]}]
set_property PACKAGE_PIN AD1 [get_ports {data_out[17]}]
set_property PACKAGE_PIN AD5 [get_ports {data_out[16]}]
set_property PACKAGE_PIN AD10 [get_ports {data_out[15]}]
set_property PACKAGE_PIN AD11 [get_ports {data_out[14]}]
set_property PACKAGE_PIN AD13 [get_ports {data_out[13]}]
set_property PACKAGE_PIN AE1 [get_ports {data_out[12]}]
set_property PACKAGE_PIN AE2 [get_ports {data_out[11]}]
set_property PACKAGE_PIN AE3 [get_ports {data_out[10]}]
set_property PACKAGE_PIN AE5 [get_ports {data_out[9]}]
set_property PACKAGE_PIN AE6 [get_ports {data_out[8]}]
set_property PACKAGE_PIN AE7 [get_ports {data_out[7]}]
set_property PACKAGE_PIN AE8 [get_ports {data_out[6]}]
set_property PACKAGE_PIN AE10 [get_ports {data_out[5]}]
set_property PACKAGE_PIN AE11 [get_ports {data_out[4]}]
set_property PACKAGE_PIN AE12 [get_ports {data_out[3]}]
set_property PACKAGE_PIN AE13 [get_ports {data_out[2]}]
set_property PACKAGE_PIN AF2 [get_ports {data_out[1]}]
set_property PACKAGE_PIN AF3 [get_ports {data_out[0]}]
